### ISSUE TITLE
Create a "user registration" page 

### ISSUE THREAD

**Issue by shan224** [shan224/scorekeeper#5]
As a new user, I want to register for an account on the system so my previous game history can be saved and reported to me.

We need form fields to get the input for 

email (this will be the username)
password

When the user registers an account they will be able to store and view previous scores.

**Comment by tindrum** [comment]
uses MongoDB to store user info. Also uses express-session to create persistent sessions and connect-mongo to store sessions in mongoDB (rather than in RAM). 

This code is 100% lifted from https://teamtreehouse.com/library/user-authentication-with-express-and-mongo. A lot of the pug template text still refers to the book club app that the tutorial uses.
